# ============================================
# 一键切换环境：修改 INFRA_HOST 的值即可
# 公司: 172.18.0.34
# 家里: 192.168.5.2
# ============================================
#INFRA_HOST: 172.18.0.34
INFRA_HOST: 192.168.5.2
