FROM docker.io/elasticsearch:8.17.0

# Install IK analysis plugin (version must match ES version)
RUN bin/elasticsearch-plugin install --batch https://get.infini.cloud/elasticsearch/analysis-ik/8.17.0
