server:
  port: 1089

spring:
  config:
    import: file:./config/application-env.yml
  application:
    name: mcp-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${INFRA_HOST:172.18.0.34}:5432/platform
    username: postgres
    password: postgres
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
  data:
    redis:
      host: ${INFRA_HOST:172.18.0.34}
      port: 16379
      database: 0
  cloud:
    nacos:
      discovery:
        server-addr: ${INFRA_HOST:172.18.0.34}:8848
        fail-fast: false
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      eager: false

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

sa-token:
  token-name: Authorization
  timeout: 86400
  is-read-header: true
  is-read-cookie: false

