apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - elasticsearch.yaml
  - kafka.yaml
  - minio.yaml
  - nacos.yaml
  - gateway-service.yaml
  - auth-service.yaml
  - blog-service.yaml
  - search-service.yaml
  - ai-service.yaml
  - knowledge-service.yaml
