server:
  port: 1088

spring:
  config:
    import: file:./config/application-env.yml
  application:
    name: project-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${INFRA_HOST:172.18.0.34}:5432/platform
    username: postgres
    password: postgres
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
  data:
    redis:
      host: ${INFRA_HOST:172.18.0.34}
      port: 16379
      database: 0
  cloud:
    nacos:
      discovery:
        server-addr: ${INFRA_HOST:172.18.0.34}:8848
        fail-fast: false
  kafka:
    bootstrap-servers: ${INFRA_HOST:172.18.0.34}:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

sa-token:
  token-name: Authorization
  timeout: 86400
  is-read-header: true
  is-read-cookie: false

# AI 模型配置
ai:
  models:
    default-model: mimo
    config:
      mimo:
        base-url: https://token-plan-cn.xiaomimimo.com
        api-key: tp-cezrw9xmilycqudu0pqz5u99iiii94jgeuqvs4egpezk3afq
        model: mimo-v2.5-pro
